  apiVersion: apps/v1
  kind: Deployment

  metadata:
    name: app1-dpl
    labels:
      application: app1

  spec:
    replicas: 1

    selector:
      matchLabels:
        application: app1

    template:
      metadata:
        labels:
          application: app1
          role: worker-node
      spec:
        containers:
        - name: app1
          image: aandonov/app1:latest
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          ports:
          - containerPort: 80

