apiVersion: v1
kind: Service
metadata:
  name: app1-service
  namespace: stage
spec:
  type: NodePort
  selector:
    app: web-nginx1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31180