apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: stage-
namespace: stage
resources:
  - app1-pod.yml
  - app1-svc.yml
  - app2-pod.yml
  - app2-svc.yml
replicas:
  - name: app2
    count: 1
  - name: app1
    count: 1
images:
  - name: aandonov/app2
    newName: aandonov/app2
    newTag: 1.1.8
  - name: aandonov/app1
    newName: aandonov/app1
    newTag: 1.1.2
