---
apiVersion: v1
kind: Pod
metadata:
  namespace: local
  name: app1
  labels:
    app: web
spec:
  containers:
    - name: nginx
      image: aandonov/app1:latest
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-frontend-service
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30000