apiVersion: v1
kind: Pod
metadata:
   name: app1
spec:
   containers:
   - name: app1
     image: aandonov/app1:latest
     ports:
     - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  selector:
    app: app1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 9090