apiVersion: v1
kind: Pod
metadata:
   name: app1
   namespace: local
   labels:
      app: web-nginx
spec:
   containers:
   - name: app1
     image: aandonov/app1:latest
     ports:
     - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app1-service
spec:
  type: nodePort
  selector:
    app: web-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080