apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 1 
  template:
    metadata:
    spec:
      containers:
      - name: app1
        image: app1:latest
        ports:
        - containerPort: 8080
