apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: local-application
  namespace: argocd

spec:
  project: default

  destination:
    namespace: local
    server: https://kubernetes.default.svc

  source:
    repoURL: https://github.com/theelasticband/devops
    targetRevision: klincharov
    path: cluster/overlays/local

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
