apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: stage-app
  namespace: argocd

spec:
  project: default

  destination:
    namespace: stage
    server: https://kubernetes.default.svc

  source:
    repoURL: https://github.com/theelasticband/devops/
    targetRevision: klincharov
    path: cluster/overlays/stage

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
        #    automated:
        #      prune: true
        #      selfHeal: false
