apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: stage-application
  namespace: argocd

spec:
  project: default

  destination:
    namespace: stage
    server: https://kubernetes.default.svc

  source:
    path: cluster/overlays/stage
    repoURL: https://github.com/theelasticband/devops
    targetRevision: klincharov

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
        #automated:
        #  prune: true
        #  selfHeal: false
