apiVersion: networking.istio.io/v1beta1
kind: DestinationRule

metadata: 
  name: app1-destrule
  labels: 
    application: app1

spec: 
  host: istio.local.devops.net
  
  subsets:
  - name: app1-stable
    labels:
      application: app1

  - name: app1-canary
    labels:
      application: app1
