apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- ../../base/
- ../../base/app1-deployment
- ../../base/app2-deployment
- ../../base/istio/

namePrefix: stage-

namespace: stage

labels:
  - pairs:
      environment: stage

patches:

## App - Istio VirtualService Patches: ##
- target:
    version: v1beta1
    kind: VirtualService
    name: app-vservice
  path: istio.vservice.yaml

# Istio VirtualService patches specific to app1 paths
- target:
    version: v1beta1
    kind: VirtualService
    name: app-vservice
  path: app1.vservice-paths.yaml

# Istio VirtualService patches specific to app2 paths
- target:
    version: v1beta1
    kind: VirtualService
    name: app-vservice
  path: app2.vservice-paths.yaml

## App - Istio Ingress Gateway Patches: ##
- target:
    version: v1beta1
    kind: Gateway
    name: app-gateway
  path: istio.gateway.yaml

