apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: stage-
namespace: stage
resources:
  - ../../base/
images:
  - name: aandonov/app2
    newName: aandonov/app2
    newTag: 1.1.17
  - name: aandonov/app1
    newName: aandonov/app1
    newTag: 1.1.5
patches:
  - target:
      version: v1
      kind: Service
      name: app1-service
    patch: |-
      - op: replace
        path: /spec/ports/0/nodePort
        value: 31180
  - target:
      version: v1
      kind: Service
      name: app2-service
    patch: |-
      - op: replace
        path: /spec/ports/0/nodePort
        value: 31190
