apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: stage-
namespace: stage

resources:
- ../../base/

images:
  - name: aandonov/app2
    newName: aandonov/app2
    newTag: 1.1.16
  - name: aandonov/app1
    newName: aandonov/app1
    newTag: 1.1.2

patches:
- target:
    version: v1
    kind: Service
    name: app1-service
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 31180
- target:
    version: v1
    kind: Service
    name: app2-service
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 31190

#patches:
#- target:
#    group: apps
#    version: v1
#    kind: Deployment
#    name: app1  
#  patch: |-
#    - op: replace
#      path: /spec/template/spec/containers/0/image
#      value: aandonov/app1:1.1.2
#- target:
#    group: apps
#    version: v1
#    kind: Deployment
#    name: app2  
#  patch: |-
#    - op: replace
#      path: /spec/template/spec/containers/0/image
#      value: aandonov/app2:1.1.15


