apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: stage-
namespace: stage
images:
- name: app2
- newName: https://hub.docker.com/r/aandonov/app2
  newTag: test
resources:
- pod-app1.yml
- pod-app2.yml