apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: local
  name: app1
  labels:
    app: web-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-nginx
  template:
    metadata:
      labels:
        app: web-nginx
    spec:  
      containers:
      - name: app1
        image: aandonov/app1:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app1-service
  namespace: local
spec:
  type: NodePort
  selector:
    app: web-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31080