apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: local
  name: app2
  labels:
    app: web-nginx2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-nginx2
  template:
    metadata:
      labels:
        app: web-nginx2
    spec:  
      containers:
      - name: app2
        image: aandonov/app2:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app2-service
  namespace: local
spec:
  type: NodePort
  selector:
    app: web-nginx2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31090