apiVersion: v1
kind: Service

metadata:
  name: app1-svc
  labels: 
    application: app1
    
spec:
  type: ClusterIP

  selector:
    application: app1
    role: worker-node

  ports:
  - name: http-default
    port: 80
    targetPort: 80
