apiVersion: v1
kind: Service

metadata:
  name: app2-svc
  labels: 
    application: app2
    
spec:
  type: ClusterIP

  selector:
    application: app2

  ports:
  - port: 80
    targetPort: 80
