apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  project: default
  source:
    chart: istio
    repoURL: https://istio-release.storage.googleapis.com/charts
    helm:
      releaseName: istio 
  destination:
    server: "https://kubernetes.default.svc"
    namespace: istio-system
