apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: apps-vs-local
spec:
  hosts:      
  - "*" 
  gateways:
  - gateway
  http:
  - name: app1-route
    match:
    - uri:
        prefix: "/app1"
    rewrite:
      uri: "/"
    route:
    - destination:
        host: "app1-service.local.svc.cluster.local"
        subset: local-app1-service-stable
        port:
          number: 80
      weight: 100
    - destination:
        host: "app1-service.local.svc.cluster.local"
        subset: local-app1-service-canary
        port:
          number: 80
      weight: 0
  - name: app2-route
    match:
    - uri:
        prefix: "/app2"
    rewrite:
      uri: "/"
    route:
    - destination:
        host: "app2-service.local.svc.cluster.local"
        port:
          number: 80