apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: local
resources:
- ../../base/
- ../../base/istio-gateway/istio-gateway.yaml


patches:
- target:
    version: v1beta1
    kind: Gateway
    name: gateway
  path: istio-gateway.yaml