apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: local
resources:
- ../../base/
- ../../base/istio-gateway/
- istio-vsvc.yaml
- app1-argo-rollout.yaml
- app1-destinationrule.yaml

patches:
- target:
    version: v1beta1
    kind: Gateway
    name: gateway
  path: istio-gw.yaml