apiVersion: v1
kind: Service
metadata:
  name: app2-service
  namespace: local
spec:
  type: NodePort
  selector:
    app: web-nginx2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31090