name: ci-app1

on:
  push:
    branches:
      - 'vprocopan'
      - 'main'
      - 'zgrujic'
    paths:
      - 'apps/app1/**'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        
      - 
        name: metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: aandonov/app1
          

      
      
      #-
      #  name: Docker meta
      #  id: meta
      #  uses: docker/metadata-action@v4
      #  with:
      #    images: aandonov/app1
      #    tags: |
      #      type=ref,event=branch
      #      type=ref,event=pr
      #      type=semver,pattern={{version}}
      #      type=semver,pattern={{major}}.{{minor}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push app1
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: {{ github.sha }}