name: ci-app1

on:
  push:
    branches:
      - 'zgrujic'
    paths:
      - 'apps/app1/**'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Read file contents
        id: read_file
        uses: andstor/file-reader-action@v1
        with:
          path: apps/app1/version
      - 
        name: Bump release version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{ steps.read_file.outputs.contents }}
          version-fragment: 'bug'
      - 
        name: metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: aandonov/app1
          tags: type=raw,value=${{ steps.bump_version.outputs.next-version }}
          #tags: type=raw,value=stage-v${{ steps.bump_version.outputs.next-version }}-{{sha}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push app1
        uses: docker/build-push-action@v3
        with:
          context: apps/app1/.
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
      -
        name: Update Kustomization file - STAGE
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: cluster/overlays/stage/kustomization.yaml
          propertyPath: .images[1].newTag
          value: ${{ steps.bump_version.outputs.next-version }}
          #value: stage-v${{ steps.bump_version.outputs.next-version }}-{{sha}}
          createPR: false
          branch: 'zgrujic' 
          commitChange: true
          updateFile: true
          message: 'Update app1 Image Version to ${{ steps.bump_version.outputs.next-version }}'
          commitUserName: zarkogrujic
      -
        name: Update Argo-Rollout file - LOCAL
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: cluster/overlays/local/app1-argo-rollout.yaml
          propertyPath: .spec.template.spec.containers[0].image
          value: aandonov/app1:${{ steps.bump_version.outputs.next-version }}
          createPR: false
          branch: 'zgrujic' 
          commitChange: true
          updateFile: true
          message: 'Update app1 Image Version to ${{ steps.bump_version.outputs.next-version }}'
          commitUserName: zarkogrujic    