name: ci-app1

on:
  push:
    branches:
      - 'main'
      - 'vprocopan'
      - 'zgrujic'
      - 'ajindra'
      - 'klincharov'
      - 'andonov'
      - 'zoran'
    tags:
      - 'v*'
    paths:
      - 'apps/app1/**'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history
      - 
        name: Git Version
        uses: codacy/git-version@2.2.0
        with:
          prefix: cluster-
          log-path: cluster/
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: aandonov/app1
          tags: type=raw,value=stage-{{raw}}-{{sha}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push app1
        uses: docker/build-push-action@v3
        with:
          context: apps/app1/.
          push: true
          tags: ${{ steps.meta.outputs.tags }}
